config/routes.rb
GpsMsg::Application.routes.draw do
  resources :users, except: [ :destroy ]
  resources :topics
  resources :tags
  resources :subscriptions, only: [ :index, :create, :destroy ]
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :hits, only: [ :new, :create, :destroy ]

  root :to => 'sessions#new'
  match '/signin', to: 'sessions#new'
  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :name, :creator_id
  has_many :tags, dependent: :destroy
  belongs_to :creator, class_name: 'User'
  has_many :subscriptions, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :creator_id, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :signed_in_user
  before_filter :check_if_current_user, only: [ :create, :edit, :update, :destroy ]

  def index
    @topics = Topic.all
    respond_with(@topics)
  end

  def show
    @topic = Topic.find(params[:id])
    respond_with(@topic)
  end

  def new
    @topic = Topic.new
  end

  def create
    if @topic.save
      flash[:success] = 'Topic created'
    end
    respond_with(@topic)
  end

  def edit
  end

  def update
    if @topic && @topic.update_attributes(params[:topic])
      flash[:success] = 'Topic updated'
    end
    respond_with(@topic)
  end

  def destroy
    @topic.destroy
    flash[:success] = 'Topic deleted.'
    respond_with(@topic)
  end
  
  private

    def check_if_current_user
      if params[:id]
        @topic = Topic.find(params[:id])
      elsif params[:topic]
        @topic = Topic.new(params[:topic])
      end
      redirect_if_not_current_user(@topic.creator.id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<h1>Update this topic</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@topic) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>List of Topics</h1>

<h3><div class="row">
  <div class="span2">
    Creator
  </div>
  <div class="span4">
    Topics
  </div>
</div></h3>

<% @topics.each do |topic| %>
  <div class="row">
    <div class="span2">
      <%= link_to topic.creator.name, topic.creator %>
    </div>
    <div class="span4">
      <%= link_to topic.name, topic_path(topic.id) %>
    </div>
    <div class="span1">
      <% if current_user.subscribed_topics.include?(topic) %>
        <%= link_to 'Unsubscribe',subscription_path(current_user.subscriptions.find_by_topic_id(topic.id).id),method: :delete %>
      <% else %>
        <%= link_to 'Subscribe', subscriptions_path(
            subscription: { user_id: current_user.id, topic_id: topic.id }), method: :post %>
      <% end %>
    </div>
    <% if current_user?(topic.creator) %>
      <div class="span1">
        <%= link_to 'Delete', topic_path(topic.id), method: :delete %>
      </div>
      <% hits = topic.tags.inject(0) { |sum, tag| sum+=tag.hits.length  }%>
      <div class="span1">
        <%= "#{hits} hits" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/topics/new.html.erb
<h1>Create new Topic</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@topic) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.hidden_field :creator_id, :value => current_user.id %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>
<div class="row">
  <div class="span2 offset5"
    <h4><%= link_to 'Edit topic name', edit_topic_path(@topic.id) if current_user?(@topic.creator) %></h4>
  </div>
</div>
<% @markers = [] %>

<div class="row">
  <div class="span6">
    <h3>Tags: <%= link_to 'Create new tag', new_tag_path(topic_id: @topic.id) if current_user?(@topic.creator) %></h3>
  </div>
</div>

 <div class="row">
  <div class="span6">
    <% @topic.tags.each do |tag| %>
      <% @markers << "markers=color:blue%7Clabel:S%7C#{tag.lat},#{tag.lng}" %>
      <div class="row">
         <div class="span5"><%= link_to tag.text, tag %></div>
         <div class="span1"><%= link_to '(Delete)', tag_path(tag.id), method: :delete if current_user?(@topic.creator) %></div>
      </div>
     <% end %>
  </div>
  <div class="span6">
    <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?size=500x500&sensor=false&#{@markers.join('&')}" %>
  </div>
</div>