config/routes.rb
GpsMsg::Application.routes.draw do
  resources :users, except: [ :destroy ]
  resources :topics
  resources :tags
  resources :subscriptions, only: [ :index, :create, :destroy ]
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :hits, only: [ :new, :create, :destroy ]

  root :to => 'sessions#new'
  match '/signin', to: 'sessions#new'
  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :created_topics, class_name: 'Topic', foreign_key: 'creator_id', dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribed_topics, through: :subscriptions, source: :topic
  has_many :hits, class_name: 'Hit', foreign_key: 'requester_id', dependent: :destroy
  has_many :tags_hit, through: :hits, source: :tag

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [ :index, :edit, :update, :destroy]
  before_filter :correct_user, only: [ :edit, :update, :destroy ]

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    @user = User.find(params[:id])
    respond_with(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = 'Account created.'
    end
    respond_with(@user)
  end

  def edit
  end

  def update
    if @user && @user.update_attributes(params[:user])
      sign_in @user
      flash[:success] = 'Changes saved successfully'
    end
    respond_with(@user)
  end

  private

    def correct_user
      @user = User.find(params[:id])

      redirect_if_not_current_user(@user.id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<tr>
  <td>
    <%= link_to user.name, user_path(user.id) %>
  </td>
  <td>
    <%= link_to user.email, "mailto:#{user.email}" %>
  </td>
</tr>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<h1>List of users</h1>

<table>
  <th>Name</th>
  <th>Email</th>
  <%= render @users %>
</table>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div class="row">
  <div class="span2 offset5">
    <h2><%= link_to @user.email, "mailto:#{@user.email}" %></h2>
  </div>
</div>
<h3>
  <div class="row">
    <div class="span2">
      My Topics:
    </div>
  </div>
</h3>
<div class="row">
  <div class="span6">
    <% @markers = [] %>
    <% @user.created_topics.each do |topic| %>
      <% hit_num = 0 %>
        <% topic.tags.each do |tag| %>
          <% @markers << "markers=color:blue%7Clabel:S%7C#{tag.lat},#{tag.lng}" %>
          <% hit_num += tag.hits.length%>
        <% end %>
        <div class="span4"><%= link_to "#{topic.name}(#{hit_num} hits)", topic %></div>
        <div class="span1"><%= link_to 'Delete', topic_path(topic.id), method: :delete if current_user?(@user) %></div>
    <% end %>
  </div>
  <div class="span6">
    
    <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?size=500x500&sensor=false&#{@markers.join('&')}" %>
  </div>
</div>