config/routes.rb
GpsMsg::Application.routes.draw do
  resources :users, except: [ :destroy ]
  resources :topics
  resources :tags
  resources :subscriptions, only: [ :index, :create, :destroy ]
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :hits, only: [ :new, :create, :destroy ]

  root :to => 'sessions#new'
  match '/signin', to: 'sessions#new'
  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :location, :lat, :lng, :text, :topic_id
  belongs_to :topic
  has_many :hits, dependent: :destroy

  validates :lat, presence: true
  validates :lng, presence: true
  validates :text, presence: true, length: { maximum: 140 }
  validates :topic_id, presence: true
  validates :location, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include TagsHelper

  before_filter :signed_in_user
  before_filter :check_if_current_user, only: [ :new, :create, :edit, :update, :destroy ]

  def index
    if params[:topic_id]
      @tags = Topic.find(params[:topic_id]).tags
    else
      @tags = current_user.created_topics.inject([]) { |all_tags, topic| all_tags + topic.tags }
    end
    respond_with(@tags)
  end

  def show
    @tag = Tag.find(params[:id])
    respond_with(@tag)
  end

  def new
    @topic_id = params[:topic_id]
  end

  def create
    @tag.location, @tag.lat, @tag.lng = request_coordinates(@tag.location)
    if @tag.save
      flash[:success] = 'Tag created'
    end
    respond_with(@tag)
  end

  def edit
  end

  def update
    if !params[:tag][:location].blank?
      params[:tag][:location], params[:tag][:lat], params[:tag][:lng] = 
            request_coordinates(params[:tag][:location])
    end
    if @tag && @tag.update_attributes(params[:tag])
      flash[:success] = 'Tag successfully updated'
    end
    respond_with(@tag)
  end

  def destroy
    @tag.destroy
    flash[:success] = 'Tag is deleted.'
    respond_with(@tag)
  end
  
  private

    def check_if_current_user
      if params[:topic_id]
        @tag = Tag.new( topic_id: params[:topic_id] )
      elsif params[:id]
        @tag = Tag.find(params[:id])
      elsif params[:tag]
        @tag = Tag.new(params[:tag])
      end
      redirect_if_not_current_user( Topic.find(@tag.topic_id).creator_id)
    end
end

app/helpers/tags_helper.rb
module TagsHelper

def get_google_locations(a_location)
    path = "https://maps.googleapis.com/maps/api/geocode/json"
    query_values = {
        address: "#{a_location}",
        sensor: 'false'
      }
    RestClient.get(path, { :params => query_values })
end

def request_coordinates(address)
  locations_json = get_google_locations(address)
  locations_parsed = JSON.parse(locations_json,  :symbolize_names => true)
  lat = locations_parsed[:results][0][:geometry][:location][:lat]
  lng = locations_parsed[:results][0][:geometry][:location][:lng]
  addr = locations_parsed[:results][0][:formatted_address]
  [addr, lat, lng]
end

end

app/views/tags/edit.html.erb
<h1>Update this tag</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@tag) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :text %>
      <%= f.text_field :text %>
      <%= f.label :location %>
      <%= f.text_field :location %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tags/index.html.erb
<h1>List of tags</h1>

<table>
  <tr>Tags:</tr>
  <br/>
  <% @tags.each do |tag| %>
    <tr><%= link_to tag.text, tag_path(tag.id) %></tr>
    <br/>
  <% end %>
</table>

app/views/tags/new.html.erb
<h1>Create new tag</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@tag) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :text %>
      <%= f.text_field :text %>
      <%= f.label :location %>
      <%= f.text_field :location %>
      <%= f.hidden_field :topic_id, :value => @topic_id %>
      <%= f.submit "Create tag", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tags/show.html.erb
<h1><%= @tag.text %></h1>
<h2><%= @tag.location %></h2>
<h2><%= "Latitude: #{@tag.lat}  Longitude: #{@tag.lng}" %></h2>

<div class="row">
  <div class="span12">
    <div class="span3">
      <%= link_to 'Edit tag', edit_tag_path(@tag.id) if current_user?(@tag.topic.creator) %>
    </div>
    <div class="span3">
      <%= "#{@tag.hits.length} hits" if current_user?(@tag.topic.creator) %>
    </div>
  </div>
</div>
<div class="row">
  <div class="span6">
    <h3>Found in topic: <%= link_to @tag.topic.name, @tag.topic %></h3>
  </div>
</div>

<div class="row">
  <div class="span6 offset3">
    <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@tag.lat},#{@tag.lng}&zoom=15&size=500x500&sensor=false&markers=color:blue%7Clabel:S%7C#{@tag.lat},#{@tag.lng}" %>
  </div>
</div>