config/routes.rb
GpsMsg::Application.routes.draw do
  resources :users, except: [ :destroy ]
  resources :topics
  resources :tags
  resources :subscriptions, only: [ :index, :create, :destroy ]
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :hits, only: [ :new, :create, :destroy ]

  root :to => 'sessions#new'
  match '/signin', to: 'sessions#new'
  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://hashmaplabs.com/">AppAcademy</a>
    Edward Kim
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <% if signed_in? %>
        <%= link_to "Hopup!", current_user, id: "logo" %>
      <% else %>
        <%= link_to "Hopup!", root_path, id: "logo" %>
      <% end %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", current_user || root_path %></li>
          <% if signed_in? %>
            <li><%= link_to 'Create Topic', new_topic_path %></li>
            <li><%= link_to 'All Topics', topics_path %></li>
            <li><%= link_to "Subscriptions", subscriptions_path(user_id: current_user.id) %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hopup</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>